test : it
	./automaker-list automaker-list.c
it : automaker-list
automaker-list : automaker-list.o buffer_0.o buffer_1.o buffer_2.o buffer_get.o buffer_put.o buffer_write.o str_len.o byte_chr.o byte_copy.o byte_copyr.o critbit0_contains.o critbit0_insert.o critbit0_insert.o error.o open_read.o getln.o getln2.o str_start.o str0_length.c str0_equalc.c stralloc_catb.o stralloc_copyb.o stralloc_ready.o stralloc_append.o alloc.o alloc_re.o limitmalloc_open.o limitmalloc_open_if2.o limitmalloc_close.o
	diet cc -o automaker-list automaker-list.o buffer_0.o buffer_1.o buffer_2.o buffer_get.o buffer_put.o buffer_write.o str_len.o byte_chr.o byte_copy.o byte_copyr.o critbit0_contains.o critbit0_insert.o error.o open_read.o getln.o getln2.o str_start.o str0_length.c str0_equalc.c stralloc_catb.o stralloc_copyb.o stralloc_ready.o stralloc_append.o alloc.o alloc_re.o limitmalloc_open.o limitmalloc_open_if2.c limitmalloc_close.c
automaker-list.o : automaker-list.c
	cc -c automaker-list.c
limitmalloc_open.o : limitmalloc_open.c
	cc -c limitmalloc_open.c
limitmalloc_close.o : limitmalloc_close.c
	cc -c limitmalloc_close.c
limitmalloc_open_if2.o : limitmalloc_open_if2.c
	cc -c limitmalloc_open_if2.c
buffer_1.o : buffer_1.c
	cc -c buffer_1.c
buffer_2.o : buffer_2.c
	cc -c buffer_2.c
buffer_put.o : buffer_put.c
	cc -c buffer_put.c
buffer_get.o : buffer_get.c
	cc -c buffer_get.c
buffer_write.o : buffer_write.c
	cc -c buffer_write.c
buffer_ready.o : buffer_ready.c
	cc -c buffer_ready.c
str_len.o : str_len.c
	cc -c str_len.c
byte_copy.o : byte_copy.c
	cc -c byte_copy.c
byte_copyr.o : byte_copyr.c
	cc -c byte_copyr.c
byte_chr.o : byte_chr.c
	cc -c byte_chr.c
open_read.o : open_read.c
	cc -c open_read.c
critbit0_contains.o : critbit0_contains.c
	cc -c critbit0_contains.c
critbit0_insert.o : critbit0_insert.c
	cc -c critbit0_insert.c
error.o : error.c
	cc -c error.c
getln.o : getln.c 
	cc -c getln.c
str_start.o : str_start.c
	cc -c str_start.c
str0_length.o : str0_length.c
	cc -c str0_length.c
str0_equalc.o : str0_equalc.c
	cc -c str0_equalc.c
stralloc_catb.o : stralloc_catb.c
	cc -c stralloc_catb.c
stralloc_copyb.o : stralloc_copyb.c
	cc -c stralloc_copyb.c
stralloc_ready.o : stralloc_ready.c
	cc -c stralloc_ready.c
stralloc_append.o : stralloc_append.c
	cc -c stralloc_append.c
alloc.o : alloc.c
	cc -c alloc.c
alloc_re.o : alloc_re.c
	cc -c alloc_re.c
clean : 
	rm -f *.o automaker-list
